# Generated by Django 2.0.7 on 2018-07-23 03:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_name', models.CharField(help_text='enter course name for the assessment (e.g CPSC 317)', max_length=20)),
                ('assignment', models.IntegerField(default=0, help_text='Percentage weight for assignments', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('quiz', models.IntegerField(default=0, help_text='Percentage weight for quizzes', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('midterm', models.IntegerField(default=0, help_text='Percentage weight for midterms', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('final', models.IntegerField(default=0, help_text='Percentage weight for final exam', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a course name (e.g. CPSC 317, MATH 200)', max_length=20)),
                ('avg', models.IntegerField(default=0)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Assessment')),
            ],
        ),
    ]
