# Generated by Django 2.0.7 on 2018-07-23 22:32

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('h', 'Homework'), ('q', 'Quiz'), ('m', 'Midterm'), ('f', 'Final')], default='h', help_text='Choose type of assessment (e.g Homework)', max_length=1)),
                ('grade', models.IntegerField(help_text='Enter grade for assessment', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('date_added', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='midterm',
            new_name='mt',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='quiz',
            new_name='qz',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='assignment',
        ),
        migrations.AddField(
            model_name='assessment',
            name='hw',
            field=models.IntegerField(default=0, help_text='Percentage weight for homeworks', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='assessment',
            field=models.OneToOneField(help_text='enter an assessment for this course', on_delete=django.db.models.deletion.CASCADE, to='dashboard.Assessment'),
        ),
        migrations.AddField(
            model_name='grades',
            name='course',
            field=models.OneToOneField(help_text='choose the course for the grade', on_delete=django.db.models.deletion.CASCADE, to='dashboard.Course'),
        ),
    ]
