# Generated by Django 2.0.7 on 2018-07-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180723_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='hw',
            new_name='homeworks',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='mt',
            new_name='midterm',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='qz',
            new_name='quizzes',
        ),
    ]
