# Generated by Django 2.0.7 on 2018-07-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180723_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='assessment_name',
            new_name='course_name',
        ),
        migrations.AddField(
            model_name='grades',
            name='assessment_name',
            field=models.CharField(default='Homework 1', help_text='enter a name for this assessment', max_length=20),
        ),
    ]
