# Generated by Django 2.0.7 on 2018-07-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='midterm',
            new_name='midterms',
        ),
    ]
