# Generated by Django 2.0.7 on 2018-07-27 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180723_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='course_name',
        ),
    ]
