# Generated by Django 2.0.7 on 2018-07-29 22:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_assessment_course_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assessment',
            new_name='Evaluation',
        ),
        migrations.RemoveField(
            model_name='course',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='assessment_name',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='assessment_type',
        ),
        migrations.AddField(
            model_name='course',
            name='evaluation',
            field=models.OneToOneField(help_text='enter an evaluation for this course (e.x Homeworks)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Evaluation'),
        ),
        migrations.AddField(
            model_name='grades',
            name='evaluation_name',
            field=models.CharField(default='Homework 1', help_text='enter a name for this evaluation', max_length=20),
        ),
        migrations.AddField(
            model_name='grades',
            name='evaluation_type',
            field=models.CharField(choices=[('h', 'Homework'), ('q', 'Quiz'), ('m', 'Midterm'), ('f', 'Final')], default='h', help_text='Choose type of evaluation (e.g Homework)', max_length=1),
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade',
            field=models.IntegerField(help_text='Enter grade (ex. 83)', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
    atomic = False
