# Generated by Django 2.0.7 on 2018-08-03 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180729_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='avg',
        ),
        migrations.RemoveField(
            model_name='course',
            name='evaluation',
        ),
        migrations.AddField(
            model_name='course',
            name='final',
            field=models.IntegerField(default=0, help_text='Percentage weight for final exam', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='course',
            name='homeworks',
            field=models.IntegerField(default=0, help_text='Percentage weight for homeworks', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='course',
            name='midterms',
            field=models.IntegerField(default=0, help_text='Percentage weight for midterms', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='course',
            name='quizzes',
            field=models.IntegerField(default=0, help_text='Percentage weight for quizzes', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
    ]
