# Generated by Django 2.0.7 on 2018-08-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180802_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='final',
            field=models.IntegerField(default=0, help_text='Percentage weight for final exam'),
        ),
        migrations.AlterField(
            model_name='course',
            name='homeworks',
            field=models.IntegerField(default=0, help_text='Percentage weight for homeworks'),
        ),
        migrations.AlterField(
            model_name='course',
            name='midterms',
            field=models.IntegerField(default=0, help_text='Percentage weight for midterms'),
        ),
        migrations.AlterField(
            model_name='course',
            name='quizzes',
            field=models.IntegerField(default=0, help_text='Percentage weight for quizzes'),
        ),
    ]
